name: GitHub Vault Secret Management

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conditional-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Run integration tests
        run: echo $PUBLIC_API_KEY_IN_LINUX
        env:
          PUBLIC_API_KEY_IN_LINUX: ${{ secrets.PUBLIC_API_KEY }}
