name: GitHub Vault Secret Management

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  conditional-echo:
    runs-on: ubuntu-latest

    steps:
      - name: Run integration tests
        run: pytest tests/test_integration.py
        env:
          PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
